C+:=gcc
Main:=main.c

APP_NAME=Application
#Flag
LDFLAGS += 


#-std=c++11
all:main.c
	#$(CXXCL) $(Main) -o $(APP_NAME) $(OBJS) $(LDFLAGS)
	$(C+)  $(Main)  -o $(APP_NAME) $(CFlag)
clean: 
	rm -f Application